name: dishwasher_timer
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.2
  flutter_launcher_icons: ^0.12.0
  build_runner: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path: "assets/clock-1.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
